config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'all_users', to: 'users#show_all_users'
  get 'friends', to: 'users#show_friends'
  get 'main', to: 'index#index', as: :index
  resources :users do
    resources :profiles
    member do
      get :follow
      get :unfollow
    end
  end
  resources :walls
  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :last_name,:name,:dob, presence: true
  mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  has_one  :profile
  has_many :walls
  has_many :friends

  paginates_per 3

  acts_as_follower
  acts_as_followable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :writer_id, presence: true
  resourcify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
    #reset_session
  end

  def render_403
    render file:"public/403.html", status:403
  end

  def render_404
    render file:"public/404.html", status:404
  end
end

app/controllers/friends_contorller.rb
class FriendsController < ApplicationController
  def create
    @friend = Friend.new(params[:friend])
    @friend.save
  end

  def destroy

  end

  private
  def friend_params
    params.require(:friend).permit(:user_id,:friend_id)
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :find_profile, only:[:show,:edit,:destroy,:update]
  before_action :set_user

  def index
    @profiles = @user.profile
    unless @profile
      render 404
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = @user.build_profile(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @profile.update_attributes(profile_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
    unless @profile
      render_404
    end
  end

  def profile_params
    params.require(:profile).permit(:last_name,:name,:middle_name,:phone,:address,:skype,:dob,:image)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @friends_1 = @user.all_following
    @friends_2 = @user.followers
    @friends = (@friends_1 + @friends_2).uniq
    @profile = @user.profile
    @wall = @user.walls.where(user_id: @user.id).order('created_at desc')
  end

  def show
    @user = User.find(params[:id])
    @wall = @user.walls.where(user_id: params[:id]).order('created_at desc')
    @friends_1 = @user.all_following
    @friends_2 = @user.followers
    @friends = (@friends_1 + @friends_2).uniq
    if @user
      @profile = @user.profile
    else
      render_404
    end
  end

  def show_friends
    @user = current_user
    @friends_1 = @user.all_following
    @friends_2 = @user.followers
    @friends = (@friends_1 + @friends_2).uniq
    @friends_count = @friends.count
  end

  def show_all_users
    @user = current_user
    @users_count = User.count
    @users = User.all.page params[:page]
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    if current_user.following?(@user)
      current_user.stop_following(@user)
    elsif @user.following?(current_user)
      @user.stop_following(current_user)
    end
  end

#-------------------------------------------
  def create

  end

  def edit

  end

  def new

  end

  def update

  end

  def destroy

  end

end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  def create
    @wall = Wall.new(wall_params)
    @wall.save
  end

  def destroy
    @wall = Wall.find(params[:id])
    @wall.destroy
  end

  private
  def wall_params
    params.require(:wall).permit(:user_id,:writer_id,:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/index.html.haml
%h1
  Main_page

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "Socialnet"
          = csrf_meta_tags
          / Le HTML5 shim, for IE6-8 support of HTML elements
          /[if lt IE 9]
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
          = stylesheet_link_tag "application", :media => "all"
          / For third-generation iPad with high-resolution Retina display:
          / Size should be 144 x 144 pixels
          = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          / For iPhone with high-resolution Retina display:
          / Size should be 114 x 114 pixels
          = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          / For first- and second-generation iPad:
          / Size should be 72 x 72 pixels
          = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          / Size should be 57 x 57 pixels
          = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          / For all other devices
          / Size should be 32 x 32 pixels
          = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
          = javascript_include_tag "application"
  %body
    .container
      .row
        .span9.pull-right
          = bootstrap_flash
          = yield
        .span3
          -if user_signed_in?
            .well.sidebar-nav
              %ul.nav.nav-list
                %li.nav-header MyPage
                %li= link_to 'Моя страница', root_path
                %li= link_to 'Мои друзья', friends_path
                %li= link_to 'Чекины'
                %li= link_to 'Все пользователи', all_users_path
                %li= link_to 'На главную', index_path
                %li= link_to 'Выйти', destroy_user_session_path, :method => :delete
      %footer
        %p &copy; MySocialNetwork 2014

app/views/layouts/trash.html.haml
-if @profile.present?
  -if @profile.image.url.present?
    %img.img-rounded{src:"#{@profile.image.url}"}
- if user_signed_in?
  %span
    hello,
    =current_user.email
  = link_to('выйти', destroy_user_session_path, :method => :delete)
- else
  = link_to('войти', new_user_session_path)
%p
  -if @profile.present?
    =link_to 'edit_profile', edit_user_profile_path(current_user,@profile)
  -else
    =link_to 'newprofile', new_user_profile_path(current_user)
%h1
  -if @profile.present?
    =@profile.name
= form_for [Wall.new],html:{class:"form-inline"} do |f|
  =f.hidden_field :writer_id, value: current_user.id
  =f.hidden_field :user_id  , value: params[:id]
  .controls
    =f.text_area :text, class:'text-field'
    =f.submit 'Send', class:'btn  btn-primary'
-@user.walls.each do |wall|
  %h5
    =wall.text
  %p
    =wall.created_at

.span3
  -if user_signed_in?
    .well
      %ul.thumbnails
        %li My Friends
        %li= link_to 'Моя страница', root_path
        %li= link_to 'Мои друзья', friends_path
        %li= link_to 'Чекины'
        %li= link_to 'Все пользователи', all_users_path
        %li= link_to 'На главную', index_path
        %li= link_to 'Выйти', destroy_user_session_path, :method => :delete

app/views/profiles/_form.html.haml
= form_for [@user,@profile] do |f|
  .control-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'text_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :middle_name, :class => 'control-label'
    .controls
      = f.text_field :middle_name, :class => 'text_field'
  .control-group
    = f.label :dob, :class => 'control-label'
    .controls
      = f.date_field :dob, :class => 'text_field'
  .control-group
    = f.label :image, :class => 'control-label'
    .controls
      = f.file_field :image, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to 'Cancel', root_path, :class => 'btn'

app/views/profiles/_profile.html.haml
.well.content
  .row
    .span10
      -if @profile
        -if @profile.image.url.present?
          %p
            %img.img-polaroid{src:"#{@profile.image.url}",width:"160px",height:"140px" }
        -else
          %p
            =image_tag "default.jpg", :class => "img-polaroid"
        %h3=profile.name
        %h3=profile.last_name
        %p Дата рождения : #{profile.dob}
      -else
        %p
          =image_tag "default.jpg", :class => "img-polaroid"
          Профиль отсутствует

app/views/profiles/edit.html.haml
%h1
  Edit
  =current_user.email
  profile
#profile_update_form.well.content
  =render 'form'

app/views/profiles/index.html.haml
.page-header
  %h1
    PROFILE
= render @profiles

app/views/profiles/new.html.haml
%h1
  NewProfile
=render 'form'

app/views/profiles/show.html.haml
.well.content
  .row
    .span10
      %h1
        = @profile.name
      %h2
        = @profile.last_name
      %p
        Дата рождения :
        = @profile.dob

app/views/users/index.html.haml
#profile_info.well.content
  =render partial: "profiles/profile", locals: {profile: @profile}
  %p
    -if @profile.present?
      =link_to 'Edit profile', edit_user_profile_path(current_user,@profile)
    -else
      =link_to 'New profile', new_user_profile_path(current_user)

#wall.well.content
  =render partial: "walls/form"
  -@wall.each do |wall|
    -isAdmin = User.find(wall.writer_id)
    -if (isAdmin.has_role?(:admin) && !(isAdmin.following?(@user) || @user.following?(isAdmin)) && isAdmin != @user)
      =render partial: "walls/wall_admin", locals: {wall: wall}
    -else
      =render partial: "walls/wall", locals: {wall: wall}

#friends_block.content.well
  %ul.thumbnails
    -@friends.each do |f|
      %li.span3.thumbnail
        =link_to "#{f.profile.name}",user_path(f)
        -if f.profile.image.url.present?
          %img{:src => "#{f.profile.image.url}"}
        -else
          =image_tag "default.jpg", :class => "img-polaroid"

app/views/users/show.html.haml
#profile_info.well.content
  =render partial: "profiles/profile", locals: {profile: @profile}
  -unless @user == current_user
    %p
      -if @user.following?(current_user) || current_user.following?(@user)
        =link_to "Удалить из друзей", unfollow_user_path(@user)
      -else
        =link_to "Добаить в друзья", follow_user_path(@user)

#wall.well.content
  -if @user.following?(current_user) || current_user.following?(@user) || @user == current_user || current_user.has_role?(:admin)
    =render partial: "walls/form"
  -@wall.each do |wall|
    -isAdmin = User.find(wall.writer_id)
    -if (isAdmin.has_role?(:admin) && !(isAdmin.following?(@user) || @user.following?(isAdmin)) && isAdmin != @user)
      =render partial: "walls/wall_admin", locals: {wall: wall}
    -else
      =render partial: "walls/wall", locals: {wall: wall}

#friends_block.content.well
  %ul.thumbnails
    -@friends.each do |f|
      %li.span3.thumbnail
        =link_to "#{f.profile.name}",user_path(f)
        -if f.profile.image.url.present?
          %img{:src => "#{f.profile.image.url}"}
        -else
          =image_tag("default.jpg")

app/views/users/show_all_users.html.haml
#users_count.well.content
  %h5
    Всего зарегистрированных пользователей:
    =@users_count

#users.well.content
  -@users.each do |u|
    -@profile = u.profile
    =render partial: "profiles/profile", locals:{profile: @profile}
    %p
      =link_to("Перейти на стрницу #{@profile.name}", current_user == u ? root_path : user_path(u))
    -if @user == u
      %p
        Не узнаёшь?Это же ты!
    -else
      %p
        -if @user.following?(u) || u.following?(@user)
          =link_to "Удалить из друзей", unfollow_user_path(u)
        -else
          =link_to "Добавить в друзья", follow_user_path(u)
  =paginate @users

app/views/users/show_friends.html.haml
#friends_count.well.content
  %h5
    -if @friends_count == 0
      У вас пока нет друзей
    -else
      Всего друзей:
      =@friends_count
#friends.well.content
  -@friends.each do |f|
    -@profile = f.profile
    =render partial: "profiles/profile", locals:{profile: @profile}
    %p
      =link_to("Перейти на страницу #{f.profile.name}", user_path(f))
    %p
      =link_to "Удалить из друзей", unfollow_user_path(f)

app/views/walls/_form.html.haml
.well.well-small.content
  = form_for [Wall.new],html:{class:"form-inline"} do |f|
    =f.hidden_field :writer_id, value: current_user.id
    =f.hidden_field :user_id  , value: params[:id] ? params[:id] : current_user.id
    .controls
      =f.text_area :text, class:'text-field'
      %br
      =f.submit 'Send', class:'btn  btn-primary'

app/views/walls/_wall.html.haml
.well.well-small.content
  .row
    .span10
      %h5
        Отправитель:
        =wall.writer_id
        (writer_id)
      %h5
        =wall.text
      %p.wall
        =wall.created_at

app/views/walls/_wall_admin.html.haml
#admin_note.well.content
  .row
    .span10
      %h5
        Отправитель:
        =wall.writer_id
        (writer_id)
      %h5
        =wall.text
      %p.wall
        =wall.created_at